apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}

          {{- if .Values.envFrom }}
          envFrom:
            {{- range .Values.envFrom }}
            - {{- if .configMapRef }}
              configMapRef:
                name: {{ .configMapRef }}
              {{- end }}
              {{- if .secretRef }}
              secretRef:
                name: {{ .secretRef }}
              {{- end }}
            {{- end }}
          {{- end }}