apiVersion: v1
name: couchdb
version: 4.6.1
appVersion: 3.3.3
description: A database featuring seamless multi-master sync, that scales from
  big data to mobile, with an intuitive HTTP/JSON API and designed for
  reliability.
keywords:
  - couchdb
  - database
  - nosql

icon: http://couchdb.apache.org/CouchDB-visual-identity/logo/CouchDB-couch-symbol.svg
