couchdb:
  clusterSize: 1
  couchdbConfig:
    couchdb:
      uuid: "REPLACE_ME_UUID"
  adminPassword: "REPLACE_ME_ADMIN_PASSWORD"
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: "gp3-encrypted"
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenScaled: Retain
    whenDeleted: Delete

secret:
  adminPassword: REPLACE_ME_ADMIN_PASSWORD
  readerPassword: REPLACE_ME_READER_PASSWORD
