apiVersion: batch/v1
kind: Job
metadata:
  name: create-couchdb-user
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: curl
          image: curlimages/curl:latest
          environment:
            - name: COUCHDB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb-secrets
                  key: admin_passwd
            - name: COUCHDB_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb-secrets
                  key: reader_passwd
          command:
            - "sh"
            - "-c"
            - |
              while ! curl -s -f http://couchdb-svc-couchdb:5984; do
                echo "Waiting for CouchDB to be ready..."
                sleep 5
              done
              curl -X PUT -u "admin:$COUCHDB_ADMIN_PASSWORD" http://couchdb-svc-couchdb:5984/_users
              curl -X PUT -u "admin:$COUCHDB_ADMIN_PASSWORD" http://couchdb-svc-couchdb:5984/_users/org.couchdb.user:reader \
                    -H "Content-Type: application/json" \
                    -d '{
                          "name": "reader",
                          "password": "'$COUCHDB_USER_PASSWORD'",
                          "roles": [],
                          "type": "user"
                        }'
          volumeMounts:
            - name: couchdb-secret
              mountPath: "/mnt/secrets"
              readOnly: true
      volumes:
        - name: couchdb-secret
          secret:
            secretName: couchdb-secrets
  backoffLimit: 3
