{{- if .Values.secretProviderClass.enabled }}
apiVersion: {{ .Values.secretProviderClass.apiVersion }}
kind: SecretProviderClass
metadata:
  name: couchdb
spec:
  {{- toYaml .Values.secretProviderClass.spec | nindent 2 }}
{{- end }}