apiVersion: v1
kind: Secret
metadata:
  name: couchdb-secrets
type: Opaque
data:
  admin_passwd: {{ .Values.secret.adminPassword | b64enc }}
  reader_passwd: {{ .Values.secret.readerPassword | b64enc }}
