{{- if .Values.secretProviderClass.enabled }}
apiVersion: {{ .Values.secretProviderClass.apiVersion }}
kind: SecretProviderClass
metadata:
  name: {{ include "couchdb.fullname" . }}-spc
spec:
  {{- toYaml .Values.secretProviderClass.spec | nindent 2 }}
{{- end }}