#
# Looks for potential secret values/sensitive data that MUST not be checked in on a Pull Request.
# See https://github.com/reviewdog/action-detect-secrets#troubleshooting for whitelisting false positives.
#
name: Detect Secrets

on: pull_request

jobs:
  detect-secrets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # v2.4.0
        name: Checkout

      # https://github.com/reviewdog/action-detect-secrets - works for pull requests only
      - name: detect-secrets
        uses: reviewdog/action-detect-secrets@master
        with:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          # see https://github.com/Yelp/detect-secrets
          # https://github.com/reviewdog/action-detect-secrets/issues/16
          detect_secrets_flags: |-
            --force-use-all-plugins 
            --exclude-files usecases/conventions/ 
            --exclude-files charts/standalone-quorum/templates/ 
            --exclude-files charts/smartcontract/templates/configmap-code.yaml 
            --exclude-files charts/fgt/config-examples/ 
            --exclude-files charts/blockchain-explorer/values.yaml 
            --exclude-files charts/blockchain-explorer/README.md
            --exclude-files charts/ethadapter/README.md
            --exclude-files charts/ethadapter/README.md.gotmpl
