#
# Runs the "Chart Releaser" https://github.com/helm/chart-releaser-action on push to main branch (e.g. on a succesful merge from a Pull Request).
# 1. The "Chart Releaser" creates a GitHub Release for each Chart that has changed
# 2. and updates the "index.yaml" of the Helm Repository in branch "gh-pages" (GitHub Pages).
#
name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # https://github.com/marketplace/actions/engineerd-configurator
      - uses: engineerd/configurator@v0.0.10
        name: Setup helm
        with:
          name: helm
          url: https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz
          pathInArchive: linux-amd64/helm
      - run: helm version

      # https://github.com/helm/chart-releaser-action
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts
          # config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GIT_TOKEN }}"
